on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
        uses: actions/checkout@v4

        run: |
          echo "MYSQL_URL=jdbc:mysql://host.docker.internal:3306/event_mng?serverTimezone=Asia/Ho_Chi_Minh&createDatabaseIfNotExist=true" > .env
          echo "MYSQLUSER=event_mng" >> .env
          echo "MYSQLPASS=123456" >> .env

        run: |
          docker rm -f event-mng || true
          docker build -t event-mng .
